collections:
  - name: community.general
  - name: https://github.com/redpanda-data/redpanda-ansible-collection.git
    type: git
    version: kafka-connect
  - name: ansible.posix
  - name: grafana.grafana
  - name: prometheus.prometheus

roles:
  - src: mrlesmithjr.mdadm
  - src: mrlesmithjr.squid
  - src: geerlingguy.node_exporter
