collections:
  - name: community.general
  - name: redpanda.cluster
    type: galaxy
  - name: ansible.posix

roles:
  - src: mrlesmithjr.mdadm
  - src: mrlesmithjr.squid
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.grafana
  - src: geerlingguy.node_exporter
