agents:
  queue: "k8s-builders"

steps:
  - label: test tiered-storage-up cluster standup ubuntu
    key: tiered-up-ubuntu
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-tier-ub --distro=ubuntu-focal --tiered=true --unstable=false --taskname=tiered-storage-cluster
    plugins:
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup ubuntu
    key: tiered-up-unstable-ubuntu
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-un-tier-ub --distro=ubuntu-focal --tiered=true --unstable=true --taskname=tiered-storage-cluster
    plugins:
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test tiered-storage-up cluster standup fedora
    key: tiered-up-fedora
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-tier-fd --distro=Fedora-Cloud-Base-34 --tiered=true --unstable=false --taskname=tiered-storage-cluster
    plugins:
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: test unstable tiered-storage-up cluster standup fedora
    key: tiered-up-unstable-fedora
    command: .buildkite/scripts/standup-cluster.sh --prefix=rp-un-tier-fd --distro=Fedora-Cloud-Base-34 --tiered=true --unstable=true --taskname=tiered-storage-cluster
    plugins:
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
