agents:
  queue: "k8s-builders"

steps:
  - label: aws ubuntu
    key: aws-up-ubuntu
    command: make ci-aws-rp -e DEPLOYMENT_ID=ci-bs-ub -e DISTRO=ubuntu-focal --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: aws ubuntu tiered
    key: aws-up-ubuntu-tiered
    command: make ci-aws-rp-tiered -e DEPLOYMENT_ID=ci-ts-ub -e DISTRO=ubuntu-focal --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: aws ubuntu tiered large
    key: aws-up-ubuntu-ts-large
    command: make ci-aws-rp-tiered -e DEPLOYMENT_ID=ci-ts-ub-lg -e DISTRO=ubuntu-focal -e INSTANCE_TYPE_AWS=is4gen.4xlarge -e MACHINE_ARCH=arm64 --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: aws fedora
    key: aws-up-fedora
    command: make ci-aws-rp -e DEPLOYMENT_ID=ci-bs-fd -e DISTRO=Fedora-Cloud-Base-36 --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: aws fedora connect
    key: aws-up-fed-con
    command: make ci-aws-rp-connect -e DEPLOYMENT_ID=ci-cn-fd -e DISTRO=Fedora-Cloud-Base-36 --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - CONNECT_RPM_TOKEN
  - label: aws fedora tiered
    key: aws-up-fedora-tiered
    command: make ci-aws-rp-tiered -e DEPLOYMENT_ID=ci-ts-fd -e DISTRO=Fedora-Cloud-Base-36 --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: aws fedora tiered connect
    key: aws-up-fed-cts
    command: make ci-aws-rp-ts-connect -e DEPLOYMENT_ID=ci-ct-fd -e DISTRO=Fedora-Cloud-Base-36 --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - CONNECT_RPM_TOKEN
  - label: aws fedora tiered large
    key: aws-up-fedora-ts-large
    command: make ci-aws-rp-tiered -e DEPLOYMENT_ID=ci-ts-fd-lg -e DISTRO=Fedora-Cloud-Base-36 -e INSTANCE_TYPE_AWS=is4gen.4xlarge -e MACHINE_ARCH=arm64 --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: gcp ubuntu basic
    key: gcp-up-ubuntu
    command: make ci-gcp-rp -e GCP_IMAGE="ubuntu-os-cloud/ubuntu-2204-lts" -e DEPLOYMENT_ID="ci-bs-ub" -e GCP_CREDS="$DEVEX_GCP_CREDS_BASE64" --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp ubuntu tiered
    key: gcp-up-ubuntu-tiered
    command: make ci-gcp-rp-tiered -e GCP_IMAGE="ubuntu-os-cloud/ubuntu-2204-lts" -e DEPLOYMENT_ID="ci-ts-ub" -e GCP_CREDS="$DEVEX_GCP_CREDS_BASE64" --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          pre-exit: make destroy-gcp
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp fedora basic
    key: gcp-up-fedora
    command: make ci-gcp-rp -e GCP_IMAGE="fedora-cloud/fedora-cloud-37" -e DEPLOYMENT_ID="ci-bs-fd" -e GCP_CREDS="$DEVEX_GCP_CREDS_BASE64" --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: gcp fedora tiered
    key: gcp-up-fedora-tiered
    command: make ci-gcp-rp-tiered -e GCP_IMAGE="fedora-cloud/fedora-cloud-37" -e DEPLOYMENT_ID="ci-ud-fd" -e GCP_CREDS="$DEVEX_GCP_CREDS_BASE64" --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DEVEX_GCP_CREDS_BASE64
  - label: unstable aws fedora tiered
    key: aws-us-fedora-tiered
    command: make ci-aws-rp-tiered -e DEPLOYMENT_ID=ci-ts-fd-us -e DISTRO=Fedora-Cloud-Base-36 -e IS_USING_UNSTABLE=true --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: unstable aws fedora tiered large
    key: aws-us-fedora-ts-large
    command: make ci-aws-rp-tiered -e DEPLOYMENT_ID=ci-ts-fd-us-lg -e DISTRO=Fedora-Cloud-Base-36 -e IS_USING_UNSTABLE=true -e INSTANCE_TYPE_AWS=is4gen.4xlarge -e MACHINE_ARCH=arm64 --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: unstable aws ubuntu tiered
    key: aws-us-ubuntu-tiered
    command: make ci-aws-rp-tiered -e DEPLOYMENT_ID=ci-ts-ub-us -e DISTRO=ubuntu-focal -e IS_USING_UNSTABLE=true --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
  - label: unstable aws ubuntu tiered large
    key: aws-us-ubuntu-ts-large
    command: make ci-aws-rp-tiered -e DEPLOYMENT_ID=ci-ts-ub-us-lg -e DISTRO=ubuntu-focal -e IS_USING_UNSTABLE=true -e INSTANCE_TYPE_AWS=is4gen.4xlarge -e MACHINE_ARCH=arm64 --keep-going
    plugins:
      - docker#v5.8.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
