---

redpanda_mode: production
redpanda_admin_api_port: 9644
redpanda_kafka_port: 9092
redpanda_rpc_port: 33145

redpanda_key_file: /etc/redpanda/certs/node.key
redpanda_cert_file: /etc/redpanda/certs/node.crt
redpanda_truststore_file: /etc/redpanda/certs/truststore.pem