- name: ensure /etc/redpanda exists
  file:
    path: /etc/redpanda
    state: directory
    mode: 0755

- name: Identify advertised ip address
  set_fact:
    advertised_ip: "{{ inventory_hostname if (advertise_public_ips | d() | bool) else private_ip }}"

- name: Reset configuration
  set_fact:
    configuration: {}

- name: Generate configurations
  set_fact:
    configuration: "{{ configuration | combine(lookup('template', custom_config_template.template) | from_yaml, recursive=True) }}"
  loop: "{{ custom_config_templates }}"
  loop_control:
    loop_var: custom_config_template
  when: custom_config_template.condition | default(True)

- name: Merge with user-provided overrides (via redpanda variable)
  set_fact:
    configuration: "{{ configuration | combine(redpanda | default({}), recursive=True) }}"

- name: Check if node looks like it's been initialized
  ansible.builtin.stat:
    path: "{{ redpanda_data_directory }}/redpanda/controller"
  register: controller_stat

- set_fact:
    is_initialized: "{{ controller_stat.stat.isdir is defined and controller_stat.stat.isdir }}"

- name: Generate Node config
  ansible.builtin.template:
    src: "redpanda.yml"
    dest: "/etc/redpanda/redpanda.yaml"
    owner: redpanda
    group: redpanda
  register: nodeconfig_result
  when: not is_initialized

- name: Generate bootstrap
  ansible.builtin.template:
    src: "bootstrap.yml"
    dest: "/etc/redpanda/.bootstrap.yaml"
    owner: redpanda
    group: redpanda
  when: not is_initialized

- name: start redpanda-tuner
  systemd:
    name: redpanda-tuner
    state: started
- name: start redpanda
  systemd:
    name: redpanda
    state: started

- name: Establish node id
  ansible.builtin.shell:
    cmd: "rpk cluster status | sed 's/*//g' | grep {{ hostvars[inventory_hostname].private_ip }} | awk '{ print $1;}'"
  register: node_id_out
  changed_when: False

- name: Set node id
  set_fact:
    node_id: "{{ node_id_out.stdout | int() }}"

- name: Establish Redpanda's current config version
  ansible.builtin.shell:
    cmd: "rpk cluster config status | awk 'BEGIN{NR!=1}{a=0}{if ($2>a) a=$2} END {print a}'"
  register: config_version
  changed_when: False
  run_once: true

- name: Set cluster config
  ansible.builtin.shell:
    cmd: "rpk cluster config set {{ item.key }} {{ item.value }}"
  loop: "{{ configuration.cluster | dict2items }}"
  register: result
  changed_when: '"New configuration version is {{ config_version.stdout|int() }}." not in result.stdout'
  run_once: true

- name: Check if restart needed
  ansible.builtin.shell:
    cmd: "rpk cluster config status | grep '^{{ node_id }} ' | awk '{ print $3 }' |  grep -E 'true|false'"
  register: restart_required_rc
  changed_when: False

- name: Generate Node config
  ansible.builtin.template:
    src: "redpanda.yml"
    dest: "/etc/redpanda/redpanda.yaml"
    owner: redpanda
    group: redpanda
  register: nodeconfig_result
  when: is_initialized

# Logic for this - restart if:
#   (
#     The rpk cluster config status says that this node requires restarting
#     OR
#     (
#      The node has been initialized (i.e. it's not a new install)
#      AND
#        (
#        The /etc/redpanda/redpanda.yaml file was changed as part of this run
#        OR
#        The package has been upgraded via apt or yum
#        )
#      )
#    )
#    AND
#    The restart_node variable has not been set to false by the user

- name: Establish whether restart required
  set_fact:
    restart_required: '("true" in restart_required_rc.stdout or (is_initialized and (nodeconfig_result.changed or "Removed" in package_result.results or "1 upgraded" in package_result.results))) and (restart_node | default("true") | bool)'

- name: Safe restart
  ansible.builtin.shell:
    cmd: "rpk cluster maintenance enable {{ node_id }} --wait && systemctl restart redpanda && rpk cluster maintenance disable {{ node_id }}"
  when: restart_required
  throttle: 1
