- hosts: redpanda[0]
  tasks:
    - name: Establish if redpanda grafana dashboard file exists
      ansible.builtin.stat:
        path: /tmp/redpanda-grafana.json
      register: dashboard

    - name: generate the redpanda grafana dashboard
      ansible.builtin.shell: |
        rpk generate grafana-dashboard --datasource prometheus --metrics-endpoint 'http://{{hostvars[inventory_hostname].private_ip}}:9644/public_metrics' > '/tmp/redpanda-grafana.json'
      when: not dashboard.stat.exists

    - name: fetch grafana dashboard
      ansible.builtin.fetch:
        src: /tmp/redpanda-grafana.json
        dest: '{{ playbook_dir }}/grafana_dashboards/redpanda-grafana.json'
        flat: true

- hosts: redpanda
  tasks:
    - name: Node dependencies - include geerlingguy nodeexporter
      ansible.builtin.include_role:
        name: geerlingguy.node_exporter

- hosts: monitor
  tasks:
    - name: install deps
      ansible.builtin.package:
        name: python3-jmespath
        state: present

- hosts: monitor
  roles:
    - cloudalchemy.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: "redpanda"
        metrics_path: "/public_metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9644') | list  }}"
      - job_name: "node"
        metrics_path: "/metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9100') | list  }}"

- hosts: monitor
  roles:
    - grafana.grafana.grafana
  vars:
    grafana_version: 9.5.7
    grafana_security:
      admin_user: admin
      admin_password: "{{ grafana_admin_pass | default('enter_your_secure_password', true) }}"
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: 1860
        revision_id: 31
        datasource: prometheus
      - dashboard_id: 7496
        revision_id: 1
        datasource: prometheus
      - dashboard_id: 18135
        revision_id: 1
        datasource: prometheus
