- hosts: redpanda
  tasks:
    - name: Include geerlingguy nodeexporter
      ansible.builtin.include_role:
        name: geerlingguy.node_exporter

- hosts: monitor
  tasks:
    - name: install deps
      ansible.builtin.package:
        name: python3-jmespath
        state: present

- name: Install certs on monitor
  hosts: monitor
  vars:
    handle_cert_install: true
    create_demo_certs: true
    root_ca_dir: "{{ playbook_dir }}/tls/ca"
    ca_cert_file: "tls/ca/ca.crt"
    redpanda_truststore_file: "/etc/redpanda/certs/ca.crt"
    node_cert_file: "tls/certs/{{ansible_hostname}}/node.crt"
  tasks:
    - name: Install and configure CA certs for running tls
      ansible.builtin.include_role:
        name: redpanda.cluster.demo_certs
      tags:
        - install_certs

- hosts: monitor
  tasks:
    - name: Create prometheus group
      ansible.builtin.group:
        name: prometheus
        state: present
        system: true
    - name: Create prometheus user
      ansible.builtin.user:
          name: prometheus
          group: prometheus
          system: true
          shell: /bin/false
          home: /var/lib/prometheus
    - name: Create /etc/redpanda directory
      ansible.builtin.file:
        path: "/etc/redpanda"
        state: directory
        owner: redpanda
        group: redpanda
        mode: "0755"
    - name: Copy CA certificate to Prometheus server
      ansible.builtin.copy:
        src: "tls/ca/ca.crt"
        dest: "/etc/redpanda/certs/ca.crt"
        mode: "0644"
        owner: prometheus
        group: prometheus

- hosts: monitor
  roles:
    - prometheus.prometheus.prometheus
  vars:
    tls: true
    prometheus_scrape_configs:
      - job_name: "redpanda"
        scheme: "https"
        metrics_path: "/public_metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9644') | list  }}"
        tls_config:
          ca_file: "/etc/redpanda/certs/ca.crt"
      - job_name: "node"
        metrics_path: "/metrics"
        static_configs:
          - targets: "{{ groups['redpanda'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9100') | list  }}"
      - job_name: "connect"
        scheme: "https"
        metrics_path: "/metrics"
        static_configs:
          - targets: "{{ groups['connect'] | map('extract', hostvars, 'inventory_hostname') | map('regex_replace', '^(.*)$','\\1:9404') | list  }}"
        tls_config:
          ca_file: "/etc/redpanda/certs/ca.crt"
#          cert_file: "/path/to/client.crt"
#          key_file: "/path/to/client.key"

- hosts: monitor
  roles:
    - grafana.grafana.grafana
  vars:
    grafana_version: 10.4.1
    grafana_security:
      admin_user: admin
      admin_password: "{{ grafana_admin_pass | default('enter_your_secure_password', true) }}"
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: 1860
        revision_id: 31
        datasource: prometheus
      - dashboard_id: 7496
        revision_id: 1
        datasource: prometheus
      - dashboard_id: 18135
        revision_id: 1
        datasource: prometheus
